# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
DISABLE_LINTERS:
  # Link checking more likely to cause false positives than be useful for us.
  - SPELL_LYCHEE
  # yamllint is sufficient for us.
  - YAML_PRETTIER
DISABLE_ERRORS_LINTERS:
  # Include spelling and grammar checks only as warnings.
  - SPELL_CSPELL
  - SPELL_PROSELINT
  - SPELL_VALE
  # These are informative but don't need to break the build.
  - COPYPASTE_JSCPD
  - MARKDOWN_MARKDOWN_LINK_CHECK
  # Hitting rate limits even with GITHUB_TOKEN.
  - REPOSITORY_TRIVY
GITHUB_COMMENT_REPORTER: false
SPELL_CSPELL_ANALYZE_FILE_NAMES: false
# Make sure Vale is setup to run with the styles it needs.
SPELL_VALE_PRE_COMMANDS:
  - command: mkdir -p styles
    cwd: "workspace"
  - command: vale sync
    cwd: "workspace"
